# Generated by Django 5.2 on 2025-05-09 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juice_app', '0002_rawmaterial_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='bottle',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='User who created this bottle size', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bottles', to=settings.AUTH_USER_MODEL),
        ),
    ]
