# Generated by Django 5.2 on 2025-05-09 20:12

import django.db.models.deletion
import django.utils.timezone
import juice_app.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juice_app', '0003_bottle_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, help_text='Payment amount', max_digits=12, validators=[juice_app.validators.validate_positive])),
                ('payment_date', models.DateField(default=django.utils.timezone.now, help_text='Date of payment')),
                ('payment_method', models.CharField(choices=[('cash', 'Cash'), ('bank_transfer', 'Bank Transfer'), ('credit_card', 'Credit Card'), ('mobile_money', 'Mobile Money'), ('cheque', 'Cheque'), ('other', 'Other')], default='cash', help_text='Method of payment', max_length=20)),
                ('reference_number', models.CharField(blank=True, help_text='Reference/transaction number for this payment', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Additional notes about this payment')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('received_by', models.ForeignKey(blank=True, help_text='User who recorded this payment', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='payments_received', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(help_text='Sale this payment applies to', on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='juice_app.sale')),
            ],
        ),
    ]
