# Generated by Django 5.2 on 2025-05-09 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('juice_app', '0004_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='reference_number',
            field=models.CharField(editable=False, help_text='System-generated reference number for this payment', max_length=50, unique=True),
        ),
    ]
